sudo: required
language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

script: gradle build -x lint